[package]
name = "pokr"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
itertools = "0.14.0"
pyo3 = { version = "0.27", features = ["extension-module"] }
pyo3-stub-gen = "0.17.2"
rand = "0.9.2"
thiserror = "2.0.17"
